# This script uses the mongod.conf.template provided and replaces all the
# environment variables generated by previous scripts
# warning this will change the mongo_common_args to add the -f flag with 
# the config file path
TEMP_CONFIG=/tmp/mongod.conf
cp ${CONTAINER_SCRIPTS_PATH}/mongod.conf.template ${TEMP_CONFIG}

# Temporary escape $$ with tags
sed 's/\$\$\([a-zA-Z_][a-zA-Z]*\)/___\1___/g' -i ${TEMP_CONFIG}

# Substitute environment variables in configuration file
TEMP=`mktemp`; cp ${TEMP_CONFIG} $TEMP; envsubst > ${TEMP_CONFIG} < $TEMP

# Gets back the temporal dollar substitution
sed 's/___\(.*\)___/\$\1/g' -i ${TEMP_CONFIG}

cp ${TEMP_CONFIG} ${MONGODB_CONFIG_PATH}

