apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: mongodb-job
  name: mongodb-job
  namespace: testmongodb
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - image: localhost:32000/performance
        imagePullPolicy: Always
        name: mongodb-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: TEST_TIME_IN_SECS
            value: "60"
          - name: REPLICASET_NAME
            value: MainRepSet
          - name: MONGO_URI
            value: mongodb://admin:mongodb123@mongod-0.mongodb.testmongodb.svc.cluster.local:27017/admin?replicaSet=MainRepSet
          - name: PARAMS
            value: -k 70 -u 5
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
